/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LawyerTabImport } from './routes/lawyer.$tab'

// Create Virtual Routes

const SearchLazyImport = createFileRoute('/search')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SearchLazyRoute = SearchLazyImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LawyerTabRoute = LawyerTabImport.update({
  id: '/lawyer/$tab',
  path: '/lawyer/$tab',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/lawyer/$tab': {
      id: '/lawyer/$tab'
      path: '/lawyer/$tab'
      fullPath: '/lawyer/$tab'
      preLoaderRoute: typeof LawyerTabImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/lawyer/$tab': typeof LawyerTabRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/lawyer/$tab': typeof LawyerTabRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_layout': typeof LayoutRoute
  '/about': typeof AboutLazyRoute
  '/search': typeof SearchLazyRoute
  '/lawyer/$tab': typeof LawyerTabRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about' | '/search' | '/lawyer/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/search' | '/lawyer/$tab'
  id: '__root__' | '/' | '/_layout' | '/about' | '/search' | '/lawyer/$tab'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LayoutRoute: typeof LayoutRoute
  AboutLazyRoute: typeof AboutLazyRoute
  SearchLazyRoute: typeof SearchLazyRoute
  LawyerTabRoute: typeof LawyerTabRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LayoutRoute: LayoutRoute,
  AboutLazyRoute: AboutLazyRoute,
  SearchLazyRoute: SearchLazyRoute,
  LawyerTabRoute: LawyerTabRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about",
        "/search",
        "/lawyer/$tab"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/search": {
      "filePath": "search.lazy.tsx"
    },
    "/lawyer/$tab": {
      "filePath": "lawyer.$tab.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
